export {default as Navbar} from "./Navbar/Navbar.jsx"
export {default as Footer} from "./Footer/Footer.jsx"
export {default as Hero} from "./Hero/Hero.jsx"
export {default as Events} from "./Events/Events.jsx"
export {default as Team} from "./Team/Team.jsx"
export {default as Gallery} from "./Gallery/Gallery.jsx"
export {default as AboutUs} from "./AboutUs/AboutUs.jsx"
export {default as ContactUs} from "./ContactUs/ContactUs.jsx"